- name: Ensure directories are created
  ansible.builtin.file:
    state: directory
    path: "{{ argocd_deploypath }}"
    mode: "0750"

- name: Ensure Argo CD namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ argocd_namespace }}"
    state: present
      
- name: Download Argo CD install manifest to control host
  ansible.builtin.get_url:
    url: "{{ argocd_manifest_url }}"
    dest: "{{ argocd_deploypath }}/install.yaml"
    mode: "0644"

- name: Apply Argo CD install manifest
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    src: "{{ argocd_deploypath }}/install.yaml"

- name: ARGOCD INSTALL | Download command line tool
  get_url:
    url: "{{ argocd_cli_url }}"
    dest: "{{ argocd_deploypath }}/argocd"
    mode: 0755

- name: Template ingress.yaml manifest
  ansible.builtin.template:
    src: ingress.yaml.j2
    dest: "{{ argocd_deploypath }}/ingress.yaml"
    mode: "0640"
  register: ingress_manifest

- name: Apply Argo CD ingress manifest
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    src: "{{ argocd_deploypath }}/ingress.yaml"
  changed_when: ingress_manifest is changed

# - name: Run the app.yaml
#   kubernetes.core.k8s:
#     # state: present
#     src: "{{ argocd_deploypath }}/app.yaml"    

#     curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
# sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
# rm argocd-linux-amd64

# - name: Install Apps

# argocd app create apps \
#     --dest-namespace argocd \
#     --dest-server https://kubernetes.default.svc \
#     --repo https://github.com/argoproj/argocd-example-apps.git \
#     --path apps  
# argocd app sync apps  
# argocd app sync -l app.kubernetes.io/instance=apps






# - name: Check for existing Argo CD TLS secret
#   ansible.builtin.command: k3s kubectl -n argocd get secret {{ cert_name }} -o name
#   register: existing_tls_secret
#   failed_when: false
#   changed_when: false

# - name: Install Argo CD TLS certificates
#   when: existing_tls_secret.stdout == ""
#   block:
#     - name: Upload TLS certificate file
#       ansible.builtin.copy:
#         src: "{{ tls_crt }}"
#         dest: "{{ argocd_deploypath }}/tls.crt"
#         mode: '0600'

#     - name: Upload TLS key file
#       ansible.builtin.copy:
#         src: "{{ tls_key }}"
#         dest: "{{ argocd_deploypath }}/tls.key"
#         mode: '0600'

#     - name: Create Kubernetes secret for Traefik TLS
#       ansible.builtin.shell: >
#         k3s kubectl create secret tls {{ cert_name }} \
#           --cert={{ argocd_deploypath }}/tls.crt \
#           --key={{ argocd_deploypath }}/tls.key \
#           -n argocd \
#           --dry-run=client -o yaml | k3s kubectl apply -f -
#       register: tls_secret_apply
#       changed_when: "'created' in tls_secret_apply.stdout or 'configured' in tls_secret_apply.stdout"
