- name: Ensure directories are created
  ansible.builtin.file:
    state: directory
    path: "{{ traefik_deploypath }}"
    mode: "0750"

- name: Configure Traefik
  ansible.builtin.import_tasks: traefik.yaml

- name: Configure Traefik dashboard
  ansible.builtin.import_tasks: dashboard.yaml
