- name: Ensure k3s manifests directory exists
  become: true
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    mode: "0755"
  
- name: Configure Traefik
  become: true
  block:
    - name: Copy Traefik HelmChartConfig manifest
      become: true
      ansible.builtin.template:
        src: traefik-helmchartconfig.yaml.j2
        dest: /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
      register: k3s_traefik_manifest

    - name: Apply Traefik HelmChartConfig manifest
      become: true
      ansible.builtin.command: k3s kubectl apply -f /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
      when: k3s_traefik_manifest is changed

