apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik
    server: {{ $config.spec.destination.server | quote }}
  project: default
  source:
    repoURL: https://github.com/jwhitaker/k8slab
    path: applications/traefik
    targetRevision: latest
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true