k3s_traefik_enabled: true
k3s_traefik_values:
  ports:
    traefik:
      expose: true
  api:
    dashboard: true
    insecure: true
  log:
    level: DEBUG
  providers:
    kubernetesIngress:
      enabled: false
    kubernetesGateway:
      enabled: true  
    kubernetesCRD:
      allowCrossNamespace: true
  ingressRoute:
    dashboard:
      enabled: true
      entryPoints: ["websecure"]
  gateway:
    listeners:
      web:
        port: 80
        protocol: HTTP
        namespacePolicy:
          from: All
      websecure:
        port: 443
        protocol: HTTPS
        namespacePolicy:
          from: All
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: "{{ cert_name }}"
            group: ""
k3s_traefik_wait_rollout: true
k3s_traefik_rollout_timeout: "120s"
